apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: clickenrent
data:
  server.properties: |
    auto.create.topics.enable=true
    log.retention.hours=168
    log.segment.bytes=1073741824
    num.partitions=3
    default.replication.factor=1
